// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"

	"github.com/gobuffalo/nulls"
)

type ChannelTransaction struct {
	ID                   int64        `json:"id"`
	TransactionStatusID  int16        `json:"transaction_status_id"`
	TransactionTypeID    int16        `json:"transaction_type_id"`
	ProgressEventID      int16        `json:"progress_event_id"`
	ChannelTransactionID nulls.String `json:"channel_transaction_id"`
	OwnerID              string       `json:"owner_id"`
	TransactionID        string       `json:"transaction_id"`
	TransactionDate      time.Time    `json:"transaction_date"`
	TransactionDatetime  time.Time    `json:"transaction_datetime"`
	CollectedAmount      float64      `json:"collected_amount"`
	SettledAmount        float64      `json:"settled_amount"`
	CreatedAt            time.Time    `json:"created_at"`
	UpdatedAt            time.Time    `json:"updated_at"`
	DeletedAt            nulls.Time   `json:"deleted_at"`
}

type MerchantTransaction struct {
	ID                    int64        `json:"id"`
	TransactionStatusID   int16        `json:"transaction_status_id"`
	TransactionTypeID     int16        `json:"transaction_type_id"`
	ProgressEventID       int16        `json:"progress_event_id"`
	MerchantTransactionID nulls.String `json:"merchant_transaction_id"`
	OwnerID               string       `json:"owner_id"`
	TransactionID         string       `json:"transaction_id"`
	TransactionDate       time.Time    `json:"transaction_date"`
	TransactionDatetime   time.Time    `json:"transaction_datetime"`
	CollectedAmount       float64      `json:"collected_amount"`
	SettledAmount         float64      `json:"settled_amount"`
	CreatedAt             time.Time    `json:"created_at"`
	UpdatedAt             time.Time    `json:"updated_at"`
	DeletedAt             nulls.Time   `json:"deleted_at"`
}

type ProductTransaction struct {
	ID                    int64        `json:"id"`
	TransactionStatusID   int16        `json:"transaction_status_id"`
	TransactionTypeID     int16        `json:"transaction_type_id"`
	ProgressEventID       nulls.Int32  `json:"progress_event_id"`
	ProductTransactionID  nulls.String `json:"product_transaction_id"`
	MerchantTransactionID nulls.String `json:"merchant_transaction_id"`
	ChannelTransactionID  nulls.String `json:"channel_transaction_id"`
	OwnerID               string       `json:"owner_id"`
	TransactionID         string       `json:"transaction_id"`
	TransactionDate       time.Time    `json:"transaction_date"`
	TransactionDatetime   time.Time    `json:"transaction_datetime"`
	CollectedAmount       float64      `json:"collected_amount"`
	SettledAmount         float64      `json:"settled_amount"`
	CreatedAt             time.Time    `json:"created_at"`
	UpdatedAt             time.Time    `json:"updated_at"`
	DeletedAt             nulls.Time   `json:"deleted_at"`
}

type ProgressEvent struct {
	ID                  int64      `json:"id"`
	ProgressEventTypeID int16      `json:"progress_event_type_id"`
	ProgressName        string     `json:"progress_name"`
	Status              string     `json:"status"`
	Percentage          float64    `json:"percentage"`
	File                string     `json:"file"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
	DeletedAt           nulls.Time `json:"deleted_at"`
}

type ProgressEventType struct {
	ID                           int64      `json:"id"`
	ProgressEventTypeName        string     `json:"progress_event_type_name"`
	ProgressEventTypeDescription string     `json:"progress_event_type_description"`
	CreatedAt                    time.Time  `json:"created_at"`
	UpdatedAt                    time.Time  `json:"updated_at"`
	DeletedAt                    nulls.Time `json:"deleted_at"`
}

type TransactionStatus struct {
	ID                int64      `json:"id"`
	StatusName        string     `json:"status_name"`
	StatusDescription string     `json:"status_description"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	DeletedAt         nulls.Time `json:"deleted_at"`
}

type TransactionType struct {
	ID              int64      `json:"id"`
	TypeName        string     `json:"type_name"`
	TypeDescription string     `json:"type_description"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	DeletedAt       nulls.Time `json:"deleted_at"`
}
